# Generated by Django 5.2.2 on 2025-10-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place_locations', '0001_initial'),
        ('tourist_spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourist_spots', to='place_locations.location'),
        ),
        migrations.AddField(
            model_name='key',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='tourist_spots.touristspot'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['nome'], name='tourist_spo_nome_4e000e_idx'),
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['is_active'], name='tourist_spo_is_acti_e8427e_idx'),
        ),
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['key'], name='key_key_725215_idx'),
        ),
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['code'], name='key_code_5964f9_idx'),
        ),
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['is_active'], name='key_is_acti_152a56_idx'),
        ),
    ]
