# Generated by Django 5.2.2 on 2025-10-24 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourist_spots', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL),
        ),
    ]