# Generated by Django 5.2.2 on 2025-10-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('tourist_spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tourist_spots.key'),
        ),
        migrations.AddIndex(
            model_name='commerce',
            index=models.Index(fields=['name'], name='commerce_name_ff2532_idx'),
        ),
        migrations.AddIndex(
            model_name='commerce',
            index=models.Index(fields=['is_active'], name='commerce_is_acti_836e82_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupon_code_c020c6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_used'], name='coupon_is_used_db1f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expires_at'], name='coupon_expires_faba28_idx'),
        ),
    ]
