# Generated by Django 5.2.2 on 2025-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_agencyprofile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='nome_agencia',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='cnpj',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='telefone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]